var gen_19 = document.getElementById('gen_19')
var ews_19 = document.getElementById('ews_19')
var pwd_19 = document.getElementById('pwd_19')
var sc_19 = document.getElementById('sc_19')
var st_19 = document.getElementById('st_19')
var text_19 = document.querySelectorAll("#cutoff-2019 td");

function general_19(){
    text_19[1].innerHTML = "59"
    text_19[3].innerHTML = "205"
    gen_19.style.color = "white"
    gen_19.style.background = "gray"
    ews_19.style.background = "white"
    ews_19.style.color = "gray"
    pwd_19.style.background = "white"
    pwd_19.style.color = "gray"
    sc_19.style.background = "white"
    sc_19.style.color = "gray"
    st_19.style.background = "white"
    st_19.style.color = "gray"
    sebc_19.style.background = "white"
    sebc_19.style.color = "gray"
    esm_19.style.background = "white"
    esm_19.style.color = "gray"
  }
function ewsc_19(){
    text_19[1].innerHTML = "-"
    text_19[3].innerHTML = "23467"
    ews_19.style.color = "white"
    ews_19.style.background = "gray"
    gen_19.style.background = "white"
    gen_19.style.color = "gray"
    pwd_19.style.background = "white"
    pwd_19.style.color = "gray"
    sc_19.style.background = "white"
    sc_19.style.color = "gray"
    st_19.style.background = "white"
    st_19.style.color = "gray"
    sebc_19.style.background = "white"
    sebc_19.style.color = "gray"
    esm_19.style.background = "white"
    esm_19.style.color = "gray"
  }
function pwdc_19(){
    text_19[1].innerHTML = "5587"
    text_19[3].innerHTML = "16758"
    pwd_19.style.color = "white"
    pwd_19.style.background = "gray"
    ews_19.style.background = "white"
    ews_19.style.color = "gray"
    pwd_19.style.background = "white"
    pwd_19.style.color = "gray"
    gen_19.style.background = "white"
    gen_19.style.color = "gray"
    st_19.style.background = "white"
    st_19.style.color = "gray"
    st_19.style.background = "white"
    st_19.style.color = "gray"
    st_19.style.background = "white"
    st_19.style.color = "gray"
  }
  function scc_19(){
    text_19[1].innerHTML = "249"
    text_19[3].innerHTML = "1504"
    sc_19.style.color = "white"
    sc_19.style.background = "gray"
    ews_19.style.background = "white"
    ews_19.style.color = "gray"
    pwd_19.style.background = "white"
    pwd_19.style.color = "gray"
    gen_19.style.background = "white"
    gen_19.style.color = "gray"
    st_19.style.background = "white"
    st_19.style.color = "gray"
    sebc_19.style.background = "white"
    sebc_19.style.color = "gray"
    esm_19.style.background = "white"
    esm_19.style.color = "gray"
  }

function stc_19(){
    text_19[1].innerHTML = "8019"
    text_19[3].innerHTML = "23873"
    st_19.style.color = "white"
    st_19.style.background = "gray"
    ews_19.style.background = "white"
    ews_19.style.color = "gray"
    pwd_19.style.background = "white"
    pwd_19.style.color = "gray"
    gen_19.style.background = "white"
    gen_19.style.color = "gray"
    sc_19.style.background = "white"
    sc_19.style.color = "gray"
    sebc_19.style.background = "white"
    sebc_19.style.color = "gray"
    esm_19.style.background = "white"
    esm_19.style.color = "gray"
  }
function sebcc_19(){
    text_19[1].innerHTML = "282"
    text_19[3].innerHTML = "690"
    sebc_19.style.color = "white"
    sebc_19.style.background = "gray"
    ews_19.style.background = "white"
    ews_19.style.color = "gray"
    pwd_19.style.background = "white"
    pwd_19.style.color = "gray"
    gen_19.style.background = "white"
    gen_19.style.color = "gray"
    sc_19.style.background = "white"
    sc_19.style.color = "gray"
    st_19.style.background = "white"
    st_19.style.color = "gray"
    esm_19.style.background = "white"
    esm_19.style.color = "gray"
  }
function esmc_19(){
    text_19[1].innerHTML = "1328"
    text_19[3].innerHTML = "2590"
    esm_19.style.color = "white"
    esm_19.style.background = "gray"
    ews_19.style.background = "white"
    ews_19.style.color = "gray"
    pwd_19.style.background = "white"
    pwd_19.style.color = "gray"
    gen_19.style.background = "white"
    gen_19.style.color = "gray"
    sc_19.style.background = "white"
    sc_19.style.color = "gray"
    st_19.style.background = "white"
    st_19.style.color = "gray"
    sebc_19.style.background = "white"
    sebc_19.style.color = "gray"
  }



var btn_20 = document.getElementsByClassName('btns')
var gen_20 = document.getElementById('gen_20')
var ews_20 = document.getElementById('ews_20')
var pwd_20 = document.getElementById('pwd_20')
var sc_20 = document.getElementById('sc_20')
var st_20 = document.getElementById('st_20')
var sebc_20 = document.getElementById('sebc_20')
var esm_20 = document.getElementById('esm_20')
var text_20 = document.querySelectorAll("#cutoff-2020 td");

function general_20(){
    text_20[1].innerHTML = "54"
    text_20[3].innerHTML = "140"
    text_20[5].innerHTML = "151"
    gen_20.style.color = "white"
    gen_20.style.background = "gray"
    ews_20.style.background = "white"
    ews_20.style.color = "gray"
    pwd_20.style.background = "white"
    pwd_20.style.color = "gray"
    sc_20.style.background = "white"
    sc_20.style.color = "gray"
    st_20.style.background = "white"
    st_20.style.color = "gray"
    sebc_20.style.background = "white"
    sebc_20.style.color = "gray"
    esm_20.style.background = "white"
    esm_20.style.color = "gray"
  }
function ewsc_20(){
    text_20[1].innerHTML = "75"
    text_20[3].innerHTML = "183"
    text_20[5].innerHTML = "194"
    ews_20.style.color = "white"
    ews_20.style.background = "gray"
    gen_20.style.background = "white"
    gen_20.style.color = "gray"
    pwd_20.style.background = "white"
    pwd_20.style.color = "gray"
    sc_20.style.background = "white"
    sc_20.style.color = "gray"
    st_20.style.background = "white"
    st_20.style.color = "gray"
    sebc_20.style.background = "white"
    sebc_20.style.color = "gray"
    esm_20.style.background = "white"
    esm_20.style.color = "gray"
  }
function pwdc_20(){
    text_20[1].innerHTML = "22541"
    text_20[3].innerHTML = "10620"
    text_20[5].innerHTML = "-"
    pwd_20.style.color = "white"
    pwd_20.style.background = "gray"
    ews_20.style.background = "white"
    ews_20.style.color = "gray"
    gen_20.style.background = "white"
    gen_20.style.color = "gray"
    sc_20.style.background = "white"
    sc_20.style.color = "gray"
    st_20.style.background = "white"
    st_20.style.color = "gray"
    sebc_20.style.background = "white"
    sebc_20.style.color = "gray"
    esm_20.style.background = "white"
    esm_20.style.color = "gray"
  }
function scc_20(){
    text_20[1].innerHTML = "1709"
    text_20[3].innerHTML = "2326"
    text_20[5].innerHTML = "657"   
    sc_20.style.color = "white"
    sc_20.style.background = "gray"
    ews_20.style.background = "white"
    ews_20.style.color = "gray"
    pwd_20.style.background = "white"
    pwd_20.style.color = "gray"
    gen_20.style.background = "white"
    gen_20.style.color = "gray"
    st_20.style.background = "white"
    st_20.style.color = "gray"
    sebc_20.style.background = "white"
    sebc_20.style.color = "gray"
    esm_20.style.background = "white"
    esm_20.style.color = "gray"
  }
function stc_20(){
    text_20[1].innerHTML = "1262"
    text_20[3].innerHTML = "11951"
    text_20[5].innerHTML = "11782"
    st_20.style.color = "white"
    st_20.style.background = "gray"
    ews_20.style.background = "white"
    ews_20.style.color = "gray"
    pwd_20.style.background = "white"
    pwd_20.style.color = "gray"
    gen_20.style.background = "white"
    gen_20.style.color = "gray"
    sc_20.style.background = "white"
    sc_20.style.color = "gray"
    sebc_20.style.background = "white"
    sebc_20.style.color = "gray"
    esm_20.style.background = "white"
    esm_20.style.color = "gray"
  }
function sebcc_20(){
    text_20[1].innerHTML = "177"
    text_20[3].innerHTML = "562"
    text_20[5].innerHTML = "238"
    sebc_20.style.color = "white"
    sebc_20.style.background = "gray"
    ews_20.style.background = "white"
    ews_20.style.color = "gray"
    pwd_20.style.background = "white"
    pwd_20.style.color = "gray"
    gen_20.style.background = "white"
    gen_20.style.color = "gray"
    sc_20.style.background = "white"
    sc_20.style.color = "gray"
    st_20.style.background = "white"
    st_20.style.color = "gray"
    esm_20.style.background = "white"
    esm_20.style.color = "gray"
  }
function esmc_20(){
    text_20[1].innerHTML = "-"
    text_20[3].innerHTML = "760"
    text_20[5].innerHTML = "197"
    esm_20.style.color = "white"
    esm_20.style.background = "gray"
    ews_20.style.background = "white"
    ews_20.style.color = "gray"
    pwd_20.style.background = "white"
    pwd_20.style.color = "gray"
    gen_20.style.background = "white"
    gen_20.style.color = "gray"
    sc_20.style.background = "white"
    sc_20.style.color = "gray"
    sebc_20.style.background = "white"
    sebc_20.style.color = "gray"
    st_20.style.background = "white"
    st_20.style.color = "gray"
  }