let suggestions =[
    "Amazon",
    "Amazon Web Services (AWS)",
    "Adobe",
    "Avizva",
    "AXA-XL",
    "Apelo",
    "Argil DX",
    "Alpha AI",
    "Aditya Birla Capital Limited",
    "Accolite Digital",
    "Apple",
    "Abhidya Tech",
    "Abyeti",
    "Byjus",
    "Bizmetric",
    "Blog Vault",
    "Board Infinity",
    "Bravura",
    "Buyhatke",
    "Bharti Airtel",
    "Cadence",
    "CAW Studios",
    "Ceasefire",
    "Chegg India",
    "Classplus",
    "Clear Trail",
    "Colt Tech",
    "CPA Global",
    "Crowe Horwath",
    "Cognizant",
    "Delhivery",
    "DE Shaw",
    "DELOITTE",
    "Darwinbox",
    "Dentalkart",
    "Ericsson Global",
    "Eagleview",
    "EkAnek",
    "Facebook",
    "FabAlley",
    "FarEye",
    "Flipkart",
    "Fico",
    "Finsol Tech",
    "Future First",
    "Genpact",
    "Goldman Sachs",
    "Google India",
    "Gradeup",
    "Grail Insights",
    "Grofers",
    "GreyB",
    "Growman Research Group",
    "GenX",
    "GeeksforGeeks",
    "Galytix",
    "Hashedin",
    "Hevodata",
    "Hitachi",
    "Hike",
    "Hyperdart",
    "IBM",
    "IIM Jobs",
    "Indus OS",
    "INFOSYS",
    "Internshala",
    "Interview Bit",
    "Jaro Toppscholars",
    "JTG",
    "KareXpert",
    "KPIT Technologies",
    "Kratikal Tech",
    "Kritikal Vision",
    "Kronos",
    "Kuliza",
    "Lumiq",
    "LG",
    "Lambda Test",
    "Leadsquared",
    "L&T Infotech",
    "LIDO",
    "Lucideus Tech",
    "Magicpin",
    "Mckinley&Rice",
    "Mtree",
    "Microsoft",
    "Morgan Stanley",
    "Netflix",
    "Nestle India",
    "Neurosensum",
    "Newage TECSCI Research",
    "NIIT Tech (now COFORGE)",
    "Oracle",
    "One Direct",
    "ORIGA",
    "OLA",
    "Optum(UHG)",
    "Optimum",
    "Octro",
    "OriServe",
    "Procol",
    "POORA",
    "P&S Market Reasearch",
    "Phillips",
    "Piggy",
    "PlaySimple",
    "Prime Seller Hub",
    "Phonepe",
    "Protiviti",
    "Publicis sapient",
    "Qualcomm",
    "Rubrik",
    "Rohde & Schwarz",
    "Reliance JIO",
    "Rockwell",
    "R System",
    "RTDS",
    "RxLogix",
    "Source Fuse",
    "Samsung",
    "Squad",
    "Sanmar Group",
    "Schindler",
    "School of Inspirational Leadership",
    "ST Microelectronics",
    "Techmahindra",
    "Tower Recharge Capital",
    "Tresvista",
    "ThoughtWorks",
    "TCS",
    "Test Book",
    "Unacademy",
    "Vitrana",
    "Vivo Mobile India",
    "VodafoneIdea",
    "Wipro",
    "Whirlpool",
    "WhitehatJR",
    "Yamaha Motors",
    "Yahoo",
    "ZinEdu",
    "ZIP loan",
    "Zyla Healthcare",
    "ZS Associates",
    "Zycus",
];